url: http://localhost:8080/_status/vars
port: 8888
bucket:
  startns: 100000 
  endns: 10000000000
  bins: 10 
  exclude: .*
  include: ^(exec_latency|txn_durations)$
custom: 
  url: postgresql://root@localhost:26257?sslmode=disable
  limit: 30
